# Generated by Django 5.0.6 on 2024-06-20 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_library_book_book_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='libary',
        ),
    ]
