# Generated by Django 5.0.6 on 2024-06-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_book_book_libary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='libary',
        ),
        migrations.AddField(
            model_name='book',
            name='library',
            field=models.ManyToManyField(null=True, to='books.library'),
        ),
    ]
